<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="SearchConsole_Module.WebForm1" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script src="Scripts/jquery-1.9.1.js" type="text/javascript"></script>
    <script src="Scripts/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    
    <script type="text/javascript" language="javascript">
        $(function () {

            $('#<%=txtStudentName.ClientID %>').autocomplete({
            source: function(request,response){
            $.ajax({
            url:"StudentService.asmx/GetStudentNames",
            data:"{'studentName':'"+ request.term +"'}",
            type:"POST",
            dataType:"json",
            contentType:"application/json;charset=utf-8",
            success: function (result) {
            
            response(result.d);
            },
            error:function(result){
            alert('there is a problem processing your request');
            }
            });
            }


        });
    });
    </script>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <p>
        Enter
        Name below:</p>
        <p>
        &nbsp;<asp:TextBox ID="txtStudentName" runat="server"></asp:TextBox>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="btnSubmit" runat="server" Text="Submit" />
    </p>
    <p>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;</p>
    <p>
        &nbsp;</p>
        <br/>
    <p>
        &nbsp;<asp:GridView 
            ID="gvStudents" runat="server" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" onrowdeleted="gvStudents_RowDeleted" 
            onrowediting="gvStudents_RowEditing" onrowupdated="gvStudents_RowUpdated" 
            onselectedindexchanged="gvStudents_SelectedIndexChanged">
        </asp:GridView>
    </p>

    </div>
    </form>
</body>
</html>
